apiVersion: apps/v1
kind: Deployment
metadata:
  name: netflix-app
  namespace: webapps
  labels:
    app: netflix-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: netflix-app
  template:
    metadata:
      labels:
        app: netflix-app
    spec:
      containers:
      - name: netflix-app
        image: jacksneel/netflix:latest
        ports:
        - containerPort: 80
        env:
        - name: TMDB_API_KEY
          valueFrom:
            secretKeyRef:
              name: tmdb-api-secret
              key: TMDB_V3_API_KEY
